services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:80"              # Laravel API на 8000
        volumes:
            - .:/var/www/html
        depends_on:
            - db

    frontend:
        image: node:20
        working_dir: /app
        volumes:
            - ./frontend:/app       # предположим, фронт в ./frontend
        ports:
            - "8080:8080"           # Vue/React dev server на 8080
        command: >
            sh -c "npm install && npm run dev"
        environment:
            - CHOKIDAR_USEPOLLING=true
        depends_on:
            - backend

    db:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_DATABASE: chat
            MYSQL_USER: user
            MYSQL_PASSWORD: user_password
        ports:
            - "3306:3306"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8081:80"
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: root_password
        depends_on:
            - db
